Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        [Required(ErrorMessage = "Please enter a first name.")]
        public string BowlerLastName { get; set; }
        [Required(ErrorMessage = "Please enter a Last name.")]
        public string BowlerFirstName { get; set; }
        public string BowlerMiddleInit { get; set; }
        [Required(ErrorMessage = "Please enter an address.")]
        public string BowlerAddress { get; set; }
        [Required(ErrorMessage = "Please enter a city.")]
        public string BowlerCity { get; set; }
        [Required(ErrorMessage = "Please enter a State.")]
        public string BowlerState { get; set; }
        [Required(ErrorMessage = "Please enter a zip.")]
        public string BowlerZip { get; set; }
        [Required(ErrorMessage = "Please enter a phone number.")]
        public string BowlerPhoneNumber { get; set; }

        // FK Relationship
        [Required(ErrorMessage = "Please select a team")]
        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

Models/BowlersDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion13.Models
{
    public class BowlersDbContext : DbContext
    {
        public BowlersDbContext(DbContextOptions<BowlersDbContext> options) : base (options)
        {
        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }
    }
}

Components/TeamsViewComponent.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using MIssion13.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion13.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private BowlersDbContext _context { get; set; }

        public TeamsViewComponent(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamID"];

            // Retrieves the list of teams for the filter
            var teams = _context.Teams.ToList();

            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MIssion13.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion13.Controllers
{
    public class HomeController : Controller
    {
        private BowlersDbContext _context { get; set; }

        public HomeController(BowlersDbContext temp)
        {
            _context = temp;
        }

        // Home page with contact info table
        public IActionResult Index(int teamid)
        {
            // Get list of bowlers from the db
            var bowlers = _context.Bowlers.ToList();
            ViewBag.TeamID = teamid;

            if (teamid == 0)
            {
                ViewBag.TeamID = 0;
                return View(bowlers);
            } 
            else
            {
                ViewBag.teamName = _context.Teams.FirstOrDefault(x => x.TeamID == teamid);
                bowlers = _context.Bowlers.Where(x => x.TeamID == teamid).ToList();
            };

            return View(bowlers);
        }

        // Display page with form to add a new bowler
        [HttpGet]
        public IActionResult NewBowler()
        {
            ViewBag.Teams = _context.Teams.ToList();

            return View();
        }

        // Submit form to add the new bowler
        [HttpPost]
        public IActionResult NewBowler(Bowler b)
        {
            if (ModelState.IsValid)
            {
                _context.Add(b);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else // if invalid
            {
                ViewBag.Teams = _context.Teams.ToList();

                return View();
            }
        }

        // Display form with selecter bowler's info to edit
        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {
            ViewBag.Teams = _context.Teams.ToList();

            // Get bowler data
            var bowler = _context.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View("NewBowler", bowler);
        }

        // Save edits to the db
        [HttpPost]
        public IActionResult Edit(Bowler b)
        {
            if (ModelState.IsValid)
            {
                _context.Update(b);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else // if invalid
            {
                ViewBag.Teams = _context.Teams.ToList();

                return View("NewBowler", b);
            }

        }

        [HttpGet]
        public IActionResult Delete(int bowlerid)
        {
            var bowler = _context.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View(bowler);
        }

        [HttpPost]
        public IActionResult Delete(Bowler b)
        {
            _context.Bowlers.Remove(b);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Home/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

@model Bowler

<div class="text-center">
    <h3>Are you sure you want to delete @Model.BowlerFirstName @Model.BowlerLastName?</h3>
</div>

<div class="row">
    <div class="col col-4"></div>
    <div class="col col-2">
        <form method="post" asp-controller="Home" asp-action="Delete">
            <button type="submit" class="btn btn-danger p-1" style="width:100%;">Delete</button>
            <input type="hidden" asp-for="BowlerID" />
        </form>
    </div>
    <div class="col col-2">
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary p-1" style="width:100%;">Cancel</a>
    </div>
    <div class="col col-4"></div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Contact Info";
}

@model List<Bowler>

<!-- Table to display bowelers -->
<table class="table table-bordered table-hover table">
    <thead class="font-weight-bold">
        <tr>
            <td>First Name</td>
            <td>Middle Initial</td>
            <td>Last Name</td>
            <td>Address</td>
            <td>City</td>
            <td>State</td>
            <td>Zip</td>
            <td>Phone Number</td>
        </tr>
    </thead>

    <tbody>
        @foreach (var b in Model)
        {
            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>

                <!-- Edit and Delete buttons -->
                <td><a class="btn btn-warning" asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID">Edit</a></td>
                <td><a class="btn btn-danger" asp-controller="Home" asp-action="Delete" asp-route-bowlerid="@b.BowlerID">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Home/NewBowler.cshtml
@{
    ViewData["Title"] = "Add a Bowler";
}

@model Bowler 

<!--Form for User to fill out-->
<form method="post" class="text-center">

    <div asp-validation-summary="All"></div>

    @*<input type="hidden" asp-for="BowlerID" />*@

    <label asp-for="BowlerFirstName">First Name:</label>
    <input asp-for="BowlerFirstName" />
    <br />

    <label asp-for="BowlerMiddleInit">Middle Initial:</label>
    <input asp-for="BowlerMiddleInit" />
    <br />

    <label asp-for="BowlerLastName">Last Name:</label>
    <input asp-for="BowlerLastName" />
    <br />

    <label asp-for="BowlerAddress">Address:</label>
    <input asp-for="BowlerAddress" />
    <br />

    <label asp-for="BowlerCity">City:</label>
    <input asp-for="BowlerCity" />
    <br />

    <label asp-for="BowlerState">State:</label>
    <input asp-for="BowlerState" />
    <br />

    <label asp-for="BowlerZip">Zip:</label>
    <input asp-for="BowlerZip" />
    <br />

    <label asp-for="BowlerPhoneNumber">Phone Number:</label>
    <input asp-for="BowlerPhoneNumber" />
    <br />

    <label asp-for="TeamID">Team: </label>
    <select asp-for="TeamID">
        <option value="">Select a Team</option>
        @foreach (Team t in ViewBag.Teams)
        {
            <option value="@t.TeamID">@t.TeamName</option>
        }
    </select>
    <br />
    <br />

    <button type="submit" class="btn btn-primary">Add Bowler</button>
</form>

Views/Shared/Components/Teams/Default.cshtml
@{
}

@model List<Team>

<div class="container-fluid">
    <!-- Button to reset the filters and display the full list of teams -->
    <a asp-controller="Home" asp-action="Index" asp-route-teamID="" class="btn btn-sm btn-primary text-center m-1">All Teams</a>

    <!-- Dynamically creates buttons for each of the team names. Can be clicked on to filter by that team -->
    @foreach (Team t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamID="@t.TeamID"
            class="btn btn-sm btn-outline-secondary text-center m-1 
            @(ViewBag.SelectedTeam == t.TeamID.ToString() ? "btn-primary" : "btn-outline-secondary")">@t.TeamName</a>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MIssion13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bowling League</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NewBowler">Add a Bowler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">

        <!--Shows the team filters-->
        <div class="row">
            <div class="col-2">
                <h5>Filter by Team:</h5>
            </div>
            <div>
                <vc:teams></vc:teams>
            </div>
        </div>

        <!-- Displays the team name header -->
        <div class="row m-2 justify-content-center">
            @if (ViewBag.teamName != null)
            {
                <h1 class="display-4">@ViewBag.teamName.TeamName</h1>
            }
        </div>
        
        <div class="row">
            <div class="col">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MIssion13
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>